// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKw1rf9cNXsxoa2V_sNmW21x8KbfRenKg',
    appId: '1:991957758896:web:bd073e1b701d5f526e9c75',
    messagingSenderId: '991957758896',
    projectId: 'final-quizlet-english',
    authDomain: 'final-quizlet-english.firebaseapp.com',
    storageBucket: 'final-quizlet-english.appspot.com',
    measurementId: 'G-B768EXSRY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzHhjSVPOiaSYl9E4OakkV-THRY_Y5ZA4',
    appId: '1:991957758896:android:e4dba378e10f5f5e6e9c75',
    messagingSenderId: '991957758896',
    projectId: 'final-quizlet-english',
    storageBucket: 'final-quizlet-english.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh261eDVXgY8qV5fKQuxHaQOQYQNtFzVU',
    appId: '1:991957758896:ios:699f7e465cf4431e6e9c75',
    messagingSenderId: '991957758896',
    projectId: 'final-quizlet-english',
    storageBucket: 'final-quizlet-english.appspot.com',
    iosClientId: '991957758896-7bcjlbr5g6nc1a9gohvigtcq6is5k30n.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalQuizletEnglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh261eDVXgY8qV5fKQuxHaQOQYQNtFzVU',
    appId: '1:991957758896:ios:699f7e465cf4431e6e9c75',
    messagingSenderId: '991957758896',
    projectId: 'final-quizlet-english',
    storageBucket: 'final-quizlet-english.appspot.com',
    iosClientId: '991957758896-7bcjlbr5g6nc1a9gohvigtcq6is5k30n.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalQuizletEnglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKw1rf9cNXsxoa2V_sNmW21x8KbfRenKg',
    appId: '1:991957758896:web:9a74824c165940b66e9c75',
    messagingSenderId: '991957758896',
    projectId: 'final-quizlet-english',
    authDomain: 'final-quizlet-english.firebaseapp.com',
    storageBucket: 'final-quizlet-english.appspot.com',
    measurementId: 'G-Q3RZ0C6FX5',
  );

}